spring:
  application:
    name: hhplus
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        timezone:
          default_storage: NORMALIZE_UTC
        jdbc:
          time_zone: UTC

---
spring:
  config:
    activate:
      on-profile: local, test

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

logging:
  level:
    root: INFO
    kr.hhplus.be.server: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.redisson: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level traceId=%X{traceId} userId=%X{userId} %logger{36} - %msg%n"

---
spring:
  data:
    redis:
      cluster:
        nodes:
          - 127.0.0.1:7100
          - 127.0.0.1:7001
          - 127.0.0.1:7002
          - 127.0.0.1:7003
          - 127.0.0.1:7004
          - 127.0.0.1:7005
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2