version: "3"

services:
  redis-node-0:
    image: redis:6.2-alpine
    container_name: redis-node-0
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7100:7000"
      - "17000:17000"
    volumes:
      - ./redis-cluster/node0/data:/data
      - ./redis-cluster/node0/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-1:
    image: redis:6.2-alpine
    container_name: redis-node-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - ./redis-cluster/node1/data:/data
      - ./redis-cluster/node1/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-2:
    image: redis:6.2-alpine
    container_name: redis-node-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./redis-cluster/node2/data:/data
      - ./redis-cluster/node2/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-3:
    image: redis:6.2-alpine
    container_name: redis-node-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - ./redis-cluster/node3/data:/data
      - ./redis-cluster/node3/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-4:
    image: redis:6.2-alpine
    container_name: redis-node-4
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - ./redis-cluster/node4/data:/data
      - ./redis-cluster/node4/redis.conf:/usr/local/etc/redis/redis.conf

  redis-node-5:
    image: redis:6.2-alpine
    container_name: redis-node-5
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - ./redis-cluster/node5/data:/data
      - ./redis-cluster/node5/redis.conf:/usr/local/etc/redis/redis.conf